version: "3.8"

services:
  web-app:
    container_name: web-app
    image: codingmanateees/sentinel-web-app:web-app
    ports:
      - "3000:3000"
    environment:
      TZ: ${TZ}

  core-api:
    container_name: core-api
    image: codingmanateees/sentinel-web-app:core-api

  detection-api:
    container_name: detection-api
    image: codingmanateees/sentinel-web-app:detection-api
    volumes:
      - ./resources/models:/app/model
      # Blueooth access
      - /var/run/dbus/:/var/run/dbus/:z
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/hailo0:/dev/hailo0
    privileged: true
    environment:
      TZ: ${TZ}
      FPS: ${FPS}
      NODE_ENV: production
      MODEL_NAME: ${MODEL_NAME}
      CAMERA_URL_LIST: ${CAMERA_URL_LIST}
      CONFIG_IMGSIZE: ${CONFIG_IMGSIZE}
      CONFIG_VERBOSE: ${CONFIG_VERBOSE}
    depends_on:
      - go2rtc

  go2rtc:
    image: alexxit/go2rtc:latest
    container_name: go2rtc
    restart: unless-stopped
    volumes:
      - ./go2rtc.config.yaml:/config/go2rtc.yaml

volumes:
  sentinel-database:
