version: "3.8"

services:
  frontend:
    container_name: sentinel-frontend
    image: codingmanateees/sentinel-web-app:frontend
    volumes:
      - sentinel-database:/app/prisma/database
    ports:
      - "3000:3000"
    environment:
      TZ: ${TZ}

  backend:
    container_name: sentinel-backend
    image: codingmanateees/sentinel-web-app:backend-base
    volumes:
      - ./model:/app/model
    ports:
      - "9002:9002"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/hailo0:/dev/hailo0
    privileged: true
    environment:
      TZ: ${TZ}
      FPS: ${FPS}
      NODE_ENV: production
      MODEL_NAME: ${MODEL_NAME}
      CAMERA_URL_LIST: ${CAMERA_URL_LIST}
      CONFIG_IMGSIZE: ${CONFIG_IMGSIZE}
      CONFIG_VERBOSE: ${CONFIG_VERBOSE}
      NEXT_SERVER_URL: ${NEXT_SERVER_URL}
    depends_on:
      - rtsp-server
      - go2rtc

  go2rtc:
    image: alexxit/go2rtc:latest
    container_name: go2rtc
    restart: unless-stopped
    volumes:
      - ./go2rtc.config.yaml:/config/go2rtc.yaml
    ports:
      - "1984:1984"
      - "8554:8554"
      - "8555:8555"

  rtsp-server:
    container_name: rtsp-server
    image: bluenviron/mediamtx:latest
    restart: unless-stopped
    environment:
      - MTX_RTSPTRANSPORTS=tcp

volumes:
  sentinel-database:
