version: "3.8"

services:
  frontend:
    container_name: sentinel-frontend
    image: codingmanateees/sentinel-web-app:demo-frontend
    volumes:
      - sentinel-database:/app/prisma/database
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Magadan
      NODE_ENV: production

  backend:
    container_name: sentinel-backend
    image: codingmanateees/sentinel-web-app:demo-backend
    volumes:
      - ./model:/app/model
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - "9002:9002"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    priviledged: true
    environment:
      TZ: Asia/Magadan
      NEXT_SERVER_URL: http://sentinel-frontend:3000/api
      CAMERA_URL_LIST: rtsp://admin:tom123123123@192.168.58.12:3200/Streaming/Channels/101
      RTSP_URL: rtsp://rtsp-server:8554
      FPS: 24
    depends_on:
      - rtsp-server
      - go2rtc

  go2rtc:
    image: alexxit/go2rtc:latest
    container_name: go2rtc
    restart: unless-stopped
    volumes:
      - ./go2rtc.config.yaml:/config/go2rtc.yaml
    ports:
      - "1984:1984"
      - "8554:8554"
      - "8555:8555"

  rtsp-server:
    container_name: rtsp-server
    image: bluenviron/mediamtx:latest
    restart: unless-stopped
    environment:
      - MTX_RTSPTRANSPORTS=tcp

volumes:
  sentinel-database:
