version: "3.8"

services:
  frontend:
    container_name: sentinel-frontend
    image: codingmanateees/sentinel-web-app:frontend-1.0.1
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Magadan
      NODE_ENV: production

  backend:
    container_name: sentinel-backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    image: codingmanateees/sentinel-web-app:backend-1.0.1
    volumes:
      - ./model:/app/model
    ports:
      - "9002:9002"
    environment:
      TZ: Asia/Magadan
      NEXT_SERVER_URL: http://sentinel-frontend:3000/api
      CAMERA_URL_LIST: rtsp://admin:tom123123123@94.247.62.214:3200/Streaming/Channels/101
      RTSP_URL: rtsp://rtsp-server:8554
      FPS: 24
    depends_on:
      - rtsp-server
      - go2rtc

  go2rtc:
    image: alexxit/go2rtc:latest
    container_name: go2rtc
    restart: unless-stopped
    volumes:
      - ./go2rtc.config.yaml:/config/go2rtc.yaml
    ports:
      - "1984:1984"
      - "8554:8554"
      - "8555:8555"

  rtsp-server:
    container_name: rtsp-server
    image: bluenviron/mediamtx:latest
    restart: unless-stopped
    environment:
      - MTX_RTSPTRANSPORTS=tcp
