events { }

http {
    upstream web_app {
        server web-app:3000;
    }

    upstream core_api {
        server core-api:8080;
    }

    upstream detection_api {
        server detection-api:9002;
    }

    upstream go2rtc {
        server go2rtc:1984;
    }

    server {
        listen 80;

        server_name _;

        location / {
            proxy_pass http://web_app;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        location /core-api/ {
            rewrite ^/core-api/?(.*)$ /$1 break;
            proxy_pass http://core_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /detection-api/ {
            rewrite ^/detection-api/?(.*)$ /$1 break;
            proxy_pass http://detection_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /go2rtc/ {
            rewrite ^/go2rtc/?(.*)$ /$1 break;
            proxy_pass http://go2rtc;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
    }
}
