name: sentinel
version: "3.8"

x-common-env: &common-env
  TZ: ${TZ}
  NODE_ENV: ${NODE_ENV}
  CORS_WHITELIST: ${CORS_WHITELIST}
  NEXT_PUBLIC_CORE_API_URL: ${CORE_API_URL}
  NEXT_PUBLIC_DETECTION_API_URL: ${DETECTION_API_URL}
  NEXT_PUBLIC_VIDEO_API_URL: ${VIDEO_API_URL}

services:
  web-app:
    container_name: web-app
    image: codingmanateees/sentinel:web-app
    ports:
      - "3000:3000"
    environment:
      <<: *common-env

  core-api:
    container_name: core-api
    environment:
      <<: *common-env
    image: codingmanateees/sentinel:core-api

  detection-api:
    container_name: detection-api
    image: codingmanateees/sentinel:detection-api
    volumes:
      - ./resources/models:/app/model
      # Blueooth access
      - /var/run/dbus/:/var/run/dbus/:z
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/hailo0:/dev/hailo0
    privileged: true
    environment:
      <<: *common-env
      FPS: 24
      MODEL_NAME: ${MODEL_NAME}
      CAMERA_URL_LIST: ${CAMERA_URL_LIST}
      CONFIG_IMGSIZE: ${CONFIG_IMGSIZE}
      CONFIG_VERBOSE: ${CONFIG_VERBOSE}
    depends_on:
      - go2rtc

  go2rtc:
    image: alexxit/go2rtc:latest
    container_name: go2rtc
    restart: unless-stopped
    volumes:
      - ./go2rtc.config.yaml:/config/go2rtc.yaml

volumes:
  sentinel-database:
